name: tetris-thefenriswolf
base: core20
version: '0.1.4.1'
summary: A terminal interface for tetris
description: |
  A terminal interface for tetris written in Haskell

grade: stable
confinement: strict

parts:
    tetris:
        plugin: nil
        source: https://github.com/samtay/tetris.git
        source-type: git
        source-commit: e3605d48f3ada54da991257920b6a139d9374ddf
        override-build: |
          mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
          stack update
          stack install --local-bin-path $SNAPCRAFT_PART_INSTALL/bin/
          chmod +x $SNAPCRAFT_PART_INSTALL/bin/tetris
        build-packages:
          - netbase
          - ncurses-base
          - gcc
          - haskell-platform
          - haskell-stack
          - cabal-install
        stage-packages:
          - ncurses-base
apps:
    tetris:
        command: ./bin/tetris

architectures:
  - build-on: [amd64]
    run-on: [amd64]
